// GENERATED from UCS/categories/*.json — do not edit by hand.
// Each UCS category carries an emoji in its category JSON (the top-level "emoji"
// field). This mirrors them for the UI. Regenerate whenever the taxonomy changes:
//   node -e (see the generator in the commit that introduced this file).

export const CATEGORY_EMOJI: Record<string, string> = {
  "AIR": "💨",
  "AIRCRAFT": "✈️",
  "ALARMS": "🚨",
  "AMBIENCE": "🌫️",
  "ANIMALS": "🐾",
  "ARCHIVED": "🗄️",
  "BEEPS": "📟",
  "BELLS": "🔔",
  "BIRDS": "🐦",
  "BOATS": "⛵",
  "BRASS": "🎺",
  "BULLETS": "🎯",
  "CARTOON": "🎪",
  "CERAMICS": "🏺",
  "CHAINS": "⛓️",
  "CHEMICALS": "🧪",
  "CLOCKS": "🕰️",
  "CLOTH": "🧵",
  "COMMUNICATIONS": "📡",
  "COMPUTERS": "💻",
  "CREATURES": "👹",
  "CROWDS": "👥",
  "CYMBALS": "💿",
  "DESIGNED": "🎨",
  "DESTRUCTION": "🏚️",
  "DIRT & SAND": "🏜️",
  "DOORS": "🚪",
  "DRAWERS": "🗃️",
  "DRUMS": "🥁",
  "ELECTRICITY": "⚡",
  "EQUIPMENT": "🧰",
  "EXPLOSIONS": "💥",
  "FARTS": "💩",
  "FIGHT": "🥊",
  "FIRE": "🔥",
  "FIREWORKS": "🎆",
  "FOLEY": "🎬",
  "FOOD & DRINK": "🍽️",
  "FOOTSTEPS": "👣",
  "GAMES": "🎮",
  "GEOTHERMAL": "♨️",
  "GLASS": "🥂",
  "GORE": "🩸",
  "GUITAR": "🎸",
  "GUNS": "🔫",
  "HORNS": "📯",
  "HUMAN": "🧍",
  "ICE": "🧊",
  "KEYBOARD": "🪗",
  "LASERS": "🔦",
  "LEATHER": "🧥",
  "LIQUID & MUD": "🫗",
  "LOOPS": "🔁",
  "MACHINES": "🏭",
  "MAGIC": "✨",
  "MALLET": "🎶",
  "MECHANICAL": "🔩",
  "METAL": "🔗",
  "MOTORS": "⚙️",
  "MOVEMENT": "🏃",
  "NATURAL DISASTER": "🌪️",
  "OBJECTS": "📦",
  "PAPER": "📄",
  "PERCUSSION": "🪘",
  "PIANO": "🎹",
  "PLASTIC": "🧴",
  "RAIN": "🌧️",
  "ROBOTS": "🤖",
  "ROCKS": "🪨",
  "ROPE": "🪢",
  "RUBBER": "🧤",
  "SCIFI": "🛸",
  "SNOW": "❄️",
  "SPORTS": "⚽",
  "STRINGS": "🎻",
  "SWOOSHES": "🌀",
  "SYNTH": "🎛️",
  "TOOLS": "🔧",
  "TOYS": "🧸",
  "TRAINS": "🚂",
  "USER INTERFACE": "🖱️",
  "VEGETATION": "🌿",
  "VEHICLES": "🚗",
  "VOCALS": "🎤",
  "VOICES": "🗣️",
  "WATER": "💧",
  "WEAPONS": "⚔️",
  "WEATHER": "🌦️",
  "WHISTLES": "😗",
  "WIND": "🌬️",
  "WINDOWS": "🪟",
  "WINGS": "🪽",
  "WOOD": "🪵",
  "WOODWIND": "🎷",
};

/** The emoji for a UCS category, or "" if unknown (e.g. "(unclassified)"). */
export function categoryEmoji(category: string): string {
  return CATEGORY_EMOJI[category] || "";
}

/** A category label for display: "🎷 WOODWIND" normally, or just "🎷" when
 *  `emojiOnly` (a column too narrow for the name). Falls back to the bare name
 *  when the category has no emoji. */
export function categoryLabel(category: string, emojiOnly = false): string {
  const e = categoryEmoji(category);
  if (!e) return category;
  return emojiOnly ? e : e + " " + category;
}
