// Rename/convert is done by generating a script the user runs locally (the
// browser can't move or resample files on disk). Each plan entry is a source →
// destination path pair; we emit a Bash, PowerShell, or Python script that
// recreates the destination tree and copies/moves each file into it — and,
// optionally, resamples it with ffmpeg on the way.

export type RenamePlan = { src: string; dest: string }[];
export type ScriptKind = 'bash' | 'powershell' | 'python';
export type Mode = 'copy' | 'move';
export type BitDepth = 'keep' | '16' | '24' | '32f';
export interface Resample { enabled: boolean; sampleRate: number; bitDepth: BitDepth }

const bashQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const psQuote = (s: string) => `"${s.replace(/`/g, '``').replace(/"/g, '`"').replace(/\$/g, '`$')}"`;

// ffmpeg PCM codec for a target bit depth (undefined → leave format unchanged).
function codecFor(bd: BitDepth): string | null {
  switch (bd) {
    case '16': return 'pcm_s16le';
    case '24': return 'pcm_s24le';
    case '32f': return 'pcm_f32le';
    default: return null;
  }
}

function bashScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const cmd = mode === 'move' ? 'mv' : 'cp';
  const codec = codecFor(rs.bitDepth);
  const out = ['#!/usr/bin/env bash', 'set -uo pipefail', '', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample → ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} — requires ffmpeg on PATH`);
  out.push('> rename_errors.log');
  out.push('');
  for (let i = 0; i < plan.length; i++) {
    const { src, dest } = plan[i];
    const dir = dest.replace(/\/[^/]*$/, '');
    out.push(`echo "[${i + 1}/${plan.length}] Processing: ${bashQuote(src)}"`);
    out.push(`mkdir -p ${bashQuote(dir)}`);
    if (rs.enabled) {
      const ffmpeg = `ffmpeg -loglevel error -y -i ${bashQuote(src)} -ar ${rs.sampleRate}${codec ? ` -c:a ${codec}` : ''} ${bashQuote(dest)}`;
      if (mode === 'move') {
        out.push(`${ffmpeg} && rm ${bashQuote(src)} || echo "Failed: ${bashQuote(src)} -> ${bashQuote(dest)}" >> rename_errors.log`);
      } else {
        out.push(`${ffmpeg} || echo "Failed: ${bashQuote(src)} -> ${bashQuote(dest)}" >> rename_errors.log`);
      }
    } else {
      out.push(`${cmd} ${bashQuote(src)} ${bashQuote(dest)} || echo "Failed: ${bashQuote(src)} -> ${bashQuote(dest)}" >> rename_errors.log`);
    }
  }
  return out.join('\n') + '\n';
}

function powershellScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const cmd = mode === 'move' ? 'Move-Item' : 'Copy-Item';
  const codec = codecFor(rs.bitDepth);
  const out = ['$ErrorActionPreference = "Continue"', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample -> ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} - requires ffmpeg on PATH`);
  out.push('Set-Content -Path "rename_errors.log" -Value ""');
  out.push('');
  for (let i = 0; i < plan.length; i++) {
    const { src, dest } = plan[i];
    const dir = dest.replace(/[\\/][^\\/]*$/, '');
    out.push(`Write-Host "[${i + 1}/${plan.length}] Processing: ${src.replace(/\$/g, '`$')}"`);
    out.push(`New-Item -ItemType Directory -Force -Path ${psQuote(dir)} | Out-Null`);
    if (rs.enabled) {
      out.push(`ffmpeg -loglevel error -y -i ${psQuote(src)} -ar ${rs.sampleRate}${codec ? ` -c:a ${codec}` : ''} ${psQuote(dest)}`);
      if (mode === 'move') out.push(`if ($?) { Remove-Item -LiteralPath ${psQuote(src)} }`);
    } else {
      out.push(`${cmd} -LiteralPath ${psQuote(src)} -Destination ${psQuote(dest)}`);
    }
    out.push(`if (!$?) { Add-Content -Path "rename_errors.log" -Value "Failed: ${psQuote(src)} -> ${psQuote(dest)}" }`);
  }
  return out.join('\r\n') + '\r\n';
}

function pythonScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const codec = codecFor(rs.bitDepth);
  const out = ['#!/usr/bin/env python3', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample → ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} — requires ffmpeg on PATH`);
  out.push('import os, shutil' + (rs.enabled ? ', subprocess' : ''), '');
  out.push(`RESAMPLE = ${rs.enabled ? 'True' : 'False'}`);
  out.push(`MOVE = ${mode === 'move' ? 'True' : 'False'}`);
  out.push(`RATE = ${rs.sampleRate}`);
  out.push(`CODEC = ${codec ? JSON.stringify(codec) : 'None'}`);
  out.push('', 'PLAN = [');
  for (const { src, dest } of plan) out.push(`    (${JSON.stringify(src)}, ${JSON.stringify(dest)}),`);
  out.push(']', '', 'with open("rename_errors.log", "w") as f: f.write("")', '');
  out.push('for i, (src, dest) in enumerate(PLAN, 1):');
  out.push('    print(f"[{i}/{len(PLAN)}] Processing: {src}")');
  out.push('    try:');
  out.push('        os.makedirs(os.path.dirname(dest), exist_ok=True)');
  out.push('        if RESAMPLE:');
  out.push('            cmd = ["ffmpeg", "-loglevel", "error", "-y", "-i", src, "-ar", str(RATE)]');
  out.push('            if CODEC: cmd += ["-c:a", CODEC]');
  out.push('            cmd.append(dest)');
  out.push('            subprocess.run(cmd, check=True)');
  out.push('            if MOVE: os.remove(src)');
  out.push('        else:');
  out.push('            (shutil.move if MOVE else shutil.copy2)(src, dest)');
  out.push('    except Exception as e:');
  out.push('        print(f"  ERROR: {e}")');
  out.push('        with open("rename_errors.log", "a") as f:');
  out.push('            f.write(f"Failed {src} -> {dest} ({e})\\n")');
  out.push('');
  return out.join('\n');
}

export function buildScript(plan: RenamePlan, kind: ScriptKind, mode: Mode, resample: Resample): { text: string; filename: string } {
  switch (kind) {
    case 'powershell': return { text: powershellScript(plan, mode, resample), filename: 'rename_samples.ps1' };
    case 'python': return { text: pythonScript(plan, mode, resample), filename: 'rename_samples.py' };
    default: return { text: bashScript(plan, mode, resample), filename: 'rename_samples.sh' };
  }
}
