// Rename/convert is done by generating a script the user runs locally (the
// browser can't move files on disk). Each plan entry is a source → destination
// path pair; we emit a Bash, PowerShell, or Python script that recreates the
// destination folder tree and copies/moves each file into it.

export type RenamePlan = { src: string; dest: string }[];
export type ScriptKind = 'bash' | 'powershell' | 'python';
export type Mode = 'copy' | 'move';

const bashQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const psQuote = (s: string) => `"${s.replace(/`/g, '``').replace(/"/g, '`"').replace(/\$/g, '`$')}"`;

function bashScript(plan: RenamePlan, mode: Mode): string {
  const cmd = mode === 'move' ? 'mv' : 'cp';
  const out = ['#!/usr/bin/env bash', 'set -euo pipefail', '', `# ${plan.length} files — generated by Scanalyzer`, ''];
  for (const { src, dest } of plan) {
    const dir = dest.replace(/\/[^/]*$/, '');
    out.push(`mkdir -p ${bashQuote(dir)}`);
    out.push(`${cmd} ${bashQuote(src)} ${bashQuote(dest)}`);
  }
  return out.join('\n') + '\n';
}

function powershellScript(plan: RenamePlan, mode: Mode): string {
  const cmd = mode === 'move' ? 'Move-Item' : 'Copy-Item';
  const out = ['$ErrorActionPreference = "Stop"', `# ${plan.length} files — generated by Scanalyzer`, ''];
  for (const { src, dest } of plan) {
    const dir = dest.replace(/[\\/][^\\/]*$/, '');
    out.push(`New-Item -ItemType Directory -Force -Path ${psQuote(dir)} | Out-Null`);
    out.push(`${cmd} -LiteralPath ${psQuote(src)} -Destination ${psQuote(dest)}`);
  }
  return out.join('\r\n') + '\r\n';
}

function pythonScript(plan: RenamePlan, mode: Mode): string {
  const fn = mode === 'move' ? 'shutil.move' : 'shutil.copy2';
  const out = ['#!/usr/bin/env python3', `# ${plan.length} files — generated by Scanalyzer`, 'import os, shutil', '', 'PLAN = ['];
  for (const { src, dest } of plan) out.push(`    (${JSON.stringify(src)}, ${JSON.stringify(dest)}),`);
  out.push(']', '', 'for src, dest in PLAN:', '    os.makedirs(os.path.dirname(dest), exist_ok=True)', `    ${fn}(src, dest)`, '');
  return out.join('\n');
}

export function buildScript(plan: RenamePlan, kind: ScriptKind, mode: Mode): { text: string; filename: string } {
  switch (kind) {
    case 'powershell': return { text: powershellScript(plan, mode), filename: 'rename_samples.ps1' };
    case 'python': return { text: pythonScript(plan, mode), filename: 'rename_samples.py' };
    default: return { text: bashScript(plan, mode), filename: 'rename_samples.sh' };
  }
}
