// Rename/convert is done by generating a script the user runs locally (the
// browser can't move or resample files on disk). Each plan entry is a source →
// destination path pair; we emit a Bash, PowerShell, or Python script that
// recreates the destination tree and copies/moves each file into it — and,
// optionally, resamples it with ffmpeg on the way.

export type RenamePlan = { src: string; dest: string }[];
export type ScriptKind = 'bash' | 'powershell' | 'python';
export type Mode = 'copy' | 'move';
export type BitDepth = 'keep' | '16' | '24' | '32f';
export interface Resample { enabled: boolean; sampleRate: number; bitDepth: BitDepth }

const bashQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const psQuote = (s: string) => `"${s.replace(/`/g, '``').replace(/"/g, '`"').replace(/\$/g, '`$')}"`;

// ffmpeg PCM codec for a target bit depth (undefined → leave format unchanged).
function codecFor(bd: BitDepth): string | null {
  switch (bd) {
    case '16': return 'pcm_s16le';
    case '24': return 'pcm_s24le';
    case '32f': return 'pcm_f32le';
    default: return null;
  }
}

function bashScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const cmd = mode === 'move' ? 'mv' : 'cp';
  const codec = codecFor(rs.bitDepth);
  const out = ['#!/usr/bin/env bash', 'set -euo pipefail', '', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample → ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} — requires ffmpeg on PATH`);
  out.push('');
  for (const { src, dest } of plan) {
    const dir = dest.replace(/\/[^/]*$/, '');
    out.push(`mkdir -p ${bashQuote(dir)}`);
    if (rs.enabled) {
      out.push(`ffmpeg -y -i ${bashQuote(src)} -ar ${rs.sampleRate}${codec ? ` -c:a ${codec}` : ''} ${bashQuote(dest)}`);
      if (mode === 'move') out.push(`rm ${bashQuote(src)}`);
    } else {
      out.push(`${cmd} ${bashQuote(src)} ${bashQuote(dest)}`);
    }
  }
  return out.join('\n') + '\n';
}

function powershellScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const cmd = mode === 'move' ? 'Move-Item' : 'Copy-Item';
  const codec = codecFor(rs.bitDepth);
  const out = ['$ErrorActionPreference = "Stop"', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample -> ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} - requires ffmpeg on PATH`);
  out.push('');
  for (const { src, dest } of plan) {
    const dir = dest.replace(/[\\/][^\\/]*$/, '');
    out.push(`New-Item -ItemType Directory -Force -Path ${psQuote(dir)} | Out-Null`);
    if (rs.enabled) {
      out.push(`ffmpeg -y -i ${psQuote(src)} -ar ${rs.sampleRate}${codec ? ` -c:a ${codec}` : ''} ${psQuote(dest)}`);
      if (mode === 'move') out.push(`Remove-Item -LiteralPath ${psQuote(src)}`);
    } else {
      out.push(`${cmd} -LiteralPath ${psQuote(src)} -Destination ${psQuote(dest)}`);
    }
  }
  return out.join('\r\n') + '\r\n';
}

function pythonScript(plan: RenamePlan, mode: Mode, rs: Resample): string {
  const codec = codecFor(rs.bitDepth);
  const out = ['#!/usr/bin/env python3', `# ${plan.length} files — generated by Scanalyzer`];
  if (rs.enabled) out.push(`# resample → ${rs.sampleRate} Hz${codec ? ` (${rs.bitDepth}-bit)` : ''} — requires ffmpeg on PATH`);
  out.push('import os, shutil' + (rs.enabled ? ', subprocess' : ''), '');
  out.push(`RESAMPLE = ${rs.enabled ? 'True' : 'False'}`);
  out.push(`MOVE = ${mode === 'move' ? 'True' : 'False'}`);
  out.push(`RATE = ${rs.sampleRate}`);
  out.push(`CODEC = ${codec ? JSON.stringify(codec) : 'None'}`);
  out.push('', 'PLAN = [');
  for (const { src, dest } of plan) out.push(`    (${JSON.stringify(src)}, ${JSON.stringify(dest)}),`);
  out.push(']', '', 'for src, dest in PLAN:', '    os.makedirs(os.path.dirname(dest), exist_ok=True)');
  out.push('    if RESAMPLE:');
  out.push('        cmd = ["ffmpeg", "-y", "-i", src, "-ar", str(RATE)]');
  out.push('        if CODEC: cmd += ["-c:a", CODEC]');
  out.push('        cmd.append(dest)');
  out.push('        subprocess.run(cmd, check=True)');
  out.push('        if MOVE: os.remove(src)');
  out.push('    else:');
  out.push('        (shutil.move if MOVE else shutil.copy2)(src, dest)', '');
  return out.join('\n');
}

export function buildScript(plan: RenamePlan, kind: ScriptKind, mode: Mode, resample: Resample): { text: string; filename: string } {
  switch (kind) {
    case 'powershell': return { text: powershellScript(plan, mode, resample), filename: 'rename_samples.ps1' };
    case 'python': return { text: pythonScript(plan, mode, resample), filename: 'rename_samples.py' };
    default: return { text: bashScript(plan, mode, resample), filename: 'rename_samples.sh' };
  }
}
