// GENERATED from UCS/categories/*.json — do not edit by hand.
// Regenerate whenever the taxonomy changes (778 subcategories, UCS v8.2.1).
//
// BACK-COMPAT SHIM. The analyzer now writes `ucs.alternatives` as objects with the
// names spelled out in full, like every other field in the .PEAK:
//
//     { category: "DOORS", subcategory: "KNOCK", id: "DOORKnck", probability: 0.31 }
//
// It used to write a single packed string of the ABBREVIATED id and a number
// ("DOORKnck 0.31"), which said nothing about which CATEGORY the id belonged to —
// hence this map. Records written by the old engine are still on disk, so the
// accessors below read BOTH forms; the map is only consulted for the old one.
// (The id prefix is not a reliable shortcut: MUSICAL is MUSC, MUSICPROD is MUSP.)

/** category_id -> [CATEGORY, SUBCATEGORY] */
export const UCS_BY_ID: Record<string, readonly [string, string]> = {
  ADR: ['ARCHIVED', 'ADR'],
  AEROBaln: ['AIRCRAFT', 'BALLOON'],
  AERODoor: ['AIRCRAFT', 'DOOR'],
  AEROHeli: ['AIRCRAFT', 'HELICOPTER'],
  AEROInt: ['AIRCRAFT', 'INTERIOR'],
  AEROJet: ['AIRCRAFT', 'JET'],
  AEROMech: ['AIRCRAFT', 'MECHANISM'],
  AEROMil: ['AIRCRAFT', 'MILITARY'],
  AEROMisc: ['AIRCRAFT', 'MISC'],
  AEROProp: ['AIRCRAFT', 'PROP'],
  AERORadio: ['AIRCRAFT', 'RADIO CONTROLLED'],
  AERORckt: ['AIRCRAFT', 'ROCKET'],
  AIRBlow: ['AIR', 'BLOW'],
  AIRBrst: ['AIR', 'BURST'],
  AIRHiss: ['AIR', 'HISS'],
  AIRMisc: ['AIR', 'MISC'],
  AIRSuck: ['AIR', 'SUCTION'],
  ALRMBell: ['ALARMS', 'BELL'],
  ALRMBuzr: ['ALARMS', 'BUZZER'],
  ALRMClok: ['ALARMS', 'CLOCK'],
  ALRMElec: ['ALARMS', 'ELECTRONIC'],
  ALRMMisc: ['ALARMS', 'MISC'],
  ALRMSirn: ['ALARMS', 'SIREN'],
  AMBAir: ['AMBIENCE', 'AIR'],
  AMBAlpn: ['AMBIENCE', 'ALPINE'],
  AMBAmus: ['AMBIENCE', 'AMUSEMENT'],
  AMBBird: ['AMBIENCE', 'BIRDSONG'],
  AMBCele: ['AMBIENCE', 'CELEBRATION'],
  AMBCnst: ['AMBIENCE', 'CONSTRUCTION'],
  AMBDsgn: ['AMBIENCE', 'DESIGNED'],
  AMBDsrt: ['AMBIENCE', 'DESERT'],
  AMBEmrg: ['AMBIENCE', 'EMERGENCY'],
  AMBFant: ['AMBIENCE', 'FANTASY'],
  AMBFarm: ['AMBIENCE', 'FARM'],
  AMBForst: ['AMBIENCE', 'FOREST'],
  AMBGras: ['AMBIENCE', 'GRASSLAND'],
  AMBHist: ['AMBIENCE', 'HISTORICAL'],
  AMBHome: ['AMBIENCE', 'RESIDENTIAL'],
  AMBHosp: ['AMBIENCE', 'HOSPITAL'],
  AMBInd: ['AMBIENCE', 'INDUSTRIAL'],
  AMBInsc: ['AMBIENCE', 'INSECT'],
  AMBLake: ['AMBIENCE', 'LAKESIDE'],
  AMBMisc: ['AMBIENCE', 'MISC'],
  AMBMrkt: ['AMBIENCE', 'MARKET'],
  AMBNaut: ['AMBIENCE', 'NAUTICAL'],
  AMBOffc: ['AMBIENCE', 'OFFICE'],
  AMBPark: ['AMBIENCE', 'PARK'],
  AMBPrisn: ['AMBIENCE', 'PRISON'],
  AMBPrtst: ['AMBIENCE', 'PROTEST'],
  AMBPubl: ['AMBIENCE', 'PUBLIC PLACE'],
  AMBRest: ['AMBIENCE', 'RESTAURANT & BAR'],
  AMBRlgn: ['AMBIENCE', 'RELIGIOUS'],
  AMBRoom: ['AMBIENCE', 'ROOM TONE'],
  AMBRurl: ['AMBIENCE', 'RURAL'],
  AMBSchl: ['AMBIENCE', 'SCHOOL'],
  AMBSci: ['AMBIENCE', 'SCIFI'],
  AMBSea: ['AMBIENCE', 'SEASIDE'],
  AMBSprt: ['AMBIENCE', 'SPORT'],
  AMBSubn: ['AMBIENCE', 'SUBURBAN'],
  AMBSwmp: ['AMBIENCE', 'SWAMP'],
  AMBTech: ['AMBIENCE', 'HITECH'],
  AMBTndra: ['AMBIENCE', 'TUNDRA'],
  AMBTown: ['AMBIENCE', 'TOWN'],
  AMBTraf: ['AMBIENCE', 'TRAFFIC'],
  AMBTran: ['AMBIENCE', 'TRANSPORTATION'],
  AMBTrop: ['AMBIENCE', 'TROPICAL'],
  AMBUndr: ['AMBIENCE', 'UNDERGROUND'],
  AMBUndwtr: ['AMBIENCE', 'UNDERWATER'],
  AMBUrbn: ['AMBIENCE', 'URBAN'],
  AMBWar: ['AMBIENCE', 'WARFARE'],
  ANMLAmph: ['ANIMALS', 'AMPHIBIAN'],
  ANMLAqua: ['ANIMALS', 'AQUATIC'],
  ANMLBat: ['ANIMALS', 'BAT'],
  ANMLCat: ['ANIMALS', 'CAT DOMESTIC'],
  ANMLDog: ['ANIMALS', 'DOG'],
  ANMLFarm: ['ANIMALS', 'FARM'],
  ANMLHors: ['ANIMALS', 'HORSE'],
  ANMLInsc: ['ANIMALS', 'INSECT'],
  ANMLMisc: ['ANIMALS', 'MISC'],
  ANMLPrim: ['ANIMALS', 'PRIMATE'],
  ANMLRdnt: ['ANIMALS', 'RODENT'],
  ANMLRept: ['ANIMALS', 'REPTILE'],
  ANMLWcat: ['ANIMALS', 'CAT WILD'],
  ANMLWdog: ['ANIMALS', 'DOG WILD'],
  ANMLWild: ['ANIMALS', 'WILD'],
  ASSET: ['ARCHIVED', 'ASSET'],
  BEEP: ['BEEPS', 'GENERAL'],
  BEEPAppl: ['BEEPS', 'APPLIANCE'],
  BEEPLofi: ['BEEPS', 'LOFI'],
  BEEPMed: ['BEEPS', 'MEDICAL'],
  BEEPTimer: ['BEEPS', 'TIMER'],
  BEEPVeh: ['BEEPS', 'VEHICLE'],
  BELLAnml: ['BELLS', 'ANIMAL'],
  BELLDoor: ['BELLS', 'DOORBELL'],
  BELLGong: ['BELLS', 'GONG'],
  BELLHand: ['BELLS', 'HANDBELL'],
  BELLLrg: ['BELLS', 'LARGE'],
  BELLMisc: ['BELLS', 'MISC'],
  BIRDCrow: ['BIRDS', 'CROW'],
  BIRDFowl: ['BIRDS', 'FOWL'],
  BIRDMisc: ['BIRDS', 'MISC'],
  BIRDPrey: ['BIRDS', 'BIRD OF PREY'],
  BIRDSea: ['BIRDS', 'SEA'],
  BIRDSong: ['BIRDS', 'SONGBIRD'],
  BIRDTrop: ['BIRDS', 'TROPICAL'],
  BIRDWade: ['BIRDS', 'WADING'],
  BLLTBy: ['BULLETS', 'BY'],
  BLLTImpt: ['BULLETS', 'IMPACT'],
  BLLTMisc: ['BULLETS', 'MISC'],
  BLLTRico: ['BULLETS', 'RICOCHET'],
  BLLTShel: ['BULLETS', 'SHELL'],
  BNCE: ['ARCHIVED', 'BOUNCE'],
  BOATAir: ['BOATS', 'AIR BOAT'],
  BOATDoor: ['BOATS', 'DOOR'],
  BOATElec: ['BOATS', 'ELECTRIC'],
  BOATFish: ['BOATS', 'FISHING'],
  BOATHorn: ['BOATS', 'HORN'],
  BOATInt: ['BOATS', 'INTERIOR'],
  BOATMech: ['BOATS', 'MECHANISM'],
  BOATMil: ['BOATS', 'MILITARY'],
  BOATMisc: ['BOATS', 'MISC'],
  BOATMotr: ['BOATS', 'MOTORBOAT'],
  BOATRace: ['BOATS', 'RACING'],
  BOATRow: ['BOATS', 'ROWBOAT'],
  BOATSail: ['BOATS', 'SAILBOAT'],
  BOATShip: ['BOATS', 'SHIP'],
  BOATStm: ['BOATS', 'STEAM'],
  BOATSub: ['BOATS', 'SUBMARINE'],
  BOATUndwtr: ['BOATS', 'UNDERWATER'],
  BOATWash: ['BOATS', 'BOW WASH'],
  CERMBrk: ['CERAMICS', 'BREAK'],
  CERMCrsh: ['CERAMICS', 'CRASH & DEBRIS'],
  CERMFric: ['CERAMICS', 'FRICTION'],
  CERMHndl: ['CERAMICS', 'HANDLE'],
  CERMImpt: ['CERAMICS', 'IMPACT'],
  CERMMisc: ['CERAMICS', 'MISC'],
  CERMMvmt: ['CERAMICS', 'MOVEMENT'],
  CERMTonl: ['CERAMICS', 'TONAL'],
  CHAINBrk: ['CHAINS', 'BREAK'],
  CHAINHndl: ['CHAINS', 'HANDLE'],
  CHAINImpt: ['CHAINS', 'IMPACT'],
  CHAINMisc: ['CHAINS', 'MISC'],
  CHAINMvmt: ['CHAINS', 'MOVEMENT'],
  CHEMAcid: ['CHEMICALS', 'ACID'],
  CHEMMisc: ['CHEMICALS', 'MISC'],
  CHEMReac: ['CHEMICALS', 'REACTION'],
  CLOCKChim: ['CLOCKS', 'CHIME'],
  CLOCKMech: ['CLOCKS', 'MECHANICS'],
  CLOCKMisc: ['CLOCKS', 'MISC'],
  CLOCKTick: ['CLOCKS', 'TICK'],
  CLOTHFlp: ['CLOTH', 'FLAP'],
  CLOTHHndl: ['CLOTH', 'HANDLE'],
  CLOTHImpt: ['CLOTH', 'IMPACT'],
  CLOTHMisc: ['CLOTH', 'MISC'],
  CLOTHMvmt: ['CLOTH', 'MOVEMENT'],
  CLOTHRip: ['CLOTH', 'RIP'],
  CMPTDriv: ['COMPUTERS', 'HARD DRIVE'],
  CMPTKey: ['COMPUTERS', 'KEYBOARD & MOUSE'],
  CMPTMisc: ['COMPUTERS', 'MISC'],
  COMAv: ['COMMUNICATIONS', 'AUDIO VISUAL'],
  COMCam: ['COMMUNICATIONS', 'CAMERA'],
  COMCell: ['COMMUNICATIONS', 'CELLPHONE'],
  COMMic: ['COMMUNICATIONS', 'MICROPHONE'],
  COMMisc: ['COMMUNICATIONS', 'MISC'],
  COMPhono: ['COMMUNICATIONS', 'PHONOGRAPH'],
  COMRadio: ['COMMUNICATIONS', 'RADIO'],
  COMStatic: ['COMMUNICATIONS', 'STATIC'],
  COMTelm: ['COMMUNICATIONS', 'TELEMETRY'],
  COMTelph: ['COMMUNICATIONS', 'TELEPHONE'],
  COMTran: ['COMMUNICATIONS', 'TRANSCEIVER'],
  COMTv: ['COMMUNICATIONS', 'TELEVISION'],
  COMType: ['COMMUNICATIONS', 'TYPEWRITER'],
  CREAAqua: ['CREATURES', 'AQUATIC'],
  CREAAvian: ['CREATURES', 'AVIAN'],
  CREABeast: ['CREATURES', 'BEAST'],
  CREABlob: ['CREATURES', 'BLOB'],
  CREADino: ['CREATURES', 'DINOSAUR'],
  CREADrgn: ['CREATURES', 'DRAGON'],
  CREAElem: ['CREATURES', 'ELEMENTAL'],
  CREAEthr: ['CREATURES', 'ETHEREAL'],
  CREAHmn: ['CREATURES', 'HUMANOID'],
  CREAInsc: ['CREATURES', 'INSECTOID'],
  CREAMisc: ['CREATURES', 'MISC'],
  CREAMnstr: ['CREATURES', 'MONSTER'],
  CREARept: ['CREATURES', 'REPTILIAN'],
  CREASmall: ['CREATURES', 'SMALL'],
  CREASrce: ['CREATURES', 'SOURCE'],
  CRWDAngr: ['CROWDS', 'ANGRY'],
  CRWDApls: ['CROWDS', 'APPLAUSE'],
  CRWDBatl: ['CROWDS', 'BATTLE'],
  CRWDCele: ['CROWDS', 'CELEBRATION'],
  CRWDCheer: ['CROWDS', 'CHEERING'],
  CRWDChld: ['CROWDS', 'CHILDREN'],
  CRWDConv: ['CROWDS', 'CONVERSATION'],
  CRWDLaff: ['CROWDS', 'LAUGHTER'],
  CRWDLoop: ['CROWDS', 'LOOP GROUP'],
  CRWDMisc: ['CROWDS', 'MISC'],
  CRWDPanic: ['CROWDS', 'PANIC'],
  CRWDQuiet: ['CROWDS', 'QUIET'],
  CRWDReac: ['CROWDS', 'REACTION'],
  CRWDSing: ['CROWDS', 'SINGING'],
  CRWDSprt: ['CROWDS', 'SPORT'],
  CRWDWalla: ['CROWDS', 'WALLA'],
  DESTRClpse: ['DESTRUCTION', 'COLLAPSE'],
  DESTRCrsh: ['DESTRUCTION', 'CRASH & DEBRIS'],
  DESTRMisc: ['DESTRUCTION', 'MISC'],
  DIRTCrsh: ['DIRT & SAND', 'CRASH & DEBRIS'],
  DIRTDust: ['DIRT & SAND', 'DUST'],
  DIRTHndl: ['DIRT & SAND', 'HANDLE'],
  DIRTImpt: ['DIRT & SAND', 'IMPACT'],
  DIRTMisc: ['DIRT & SAND', 'MISC'],
  DIRTMvmt: ['DIRT & SAND', 'MOVEMENT'],
  DIRTTonl: ['DIRT & SAND', 'TONAL'],
  DOORAntq: ['DOORS', 'ANTIQUE'],
  DOORAppl: ['DOORS', 'APPLIANCE'],
  DOORCab: ['DOORS', 'CABINET'],
  DOORComp: ['DOORS', 'COMPOSITE'],
  DOORCreak: ['DOORS', 'CREAK'],
  DOORDungn: ['DOORS', 'DUNGEON'],
  DOORElec: ['DOORS', 'ELECTRIC'],
  DOORGate: ['DOORS', 'GATE'],
  DOORGlas: ['DOORS', 'GLASS'],
  DOORHdwr: ['DOORS', 'HARDWARE'],
  DOORHydr: ['DOORS', 'HYDRAULIC & PNEUMATIC'],
  DOORKnck: ['DOORS', 'KNOCK'],
  DOORMetl: ['DOORS', 'METAL'],
  DOORMisc: ['DOORS', 'MISC'],
  DOORPlas: ['DOORS', 'PLASTIC'],
  DOORPrisn: ['DOORS', 'PRISON'],
  DOORRevl: ['DOORS', 'REVOLVING'],
  DOORSlid: ['DOORS', 'SLIDING'],
  DOORSton: ['DOORS', 'STONE'],
  DOORSwng: ['DOORS', 'SWINGING'],
  DOORTech: ['DOORS', 'HITECH'],
  DOORWood: ['DOORS', 'WOOD'],
  DRWRMetl: ['DRAWERS', 'METAL'],
  DRWRMisc: ['DRAWERS', 'MISC'],
  DRWRPlas: ['DRAWERS', 'PLASTIC'],
  DRWRWood: ['DRAWERS', 'WOOD'],
  DSGNBass: ['DESIGNED', 'BASS DIVE'],
  DSGNBoom: ['DESIGNED', 'BOOM'],
  DSGNBram: ['DESIGNED', 'BRAAM'],
  DSGNDist: ['DESIGNED', 'DISTORTION'],
  DSGNDron: ['DESIGNED', 'DRONE'],
  DSGNErie: ['DESIGNED', 'EERIE'],
  DSGNEthr: ['DESIGNED', 'ETHEREAL'],
  DSGNGran: ['DESIGNED', 'GRANULAR'],
  DSGNImpt: ['DESIGNED', 'IMPACT'],
  DSGNMisc: ['DESIGNED', 'MISC'],
  DSGNMorph: ['DESIGNED', 'MORPH'],
  DSGNRise: ['DESIGNED', 'RISER'],
  DSGNRmbl: ['DESIGNED', 'RUMBLE'],
  DSGNRythm: ['DESIGNED', 'RHYTHMIC'],
  DSGNSrce: ['DESIGNED', 'SOURCE'],
  DSGNStngr: ['DESIGNED', 'STINGER'],
  DSGNSynth: ['DESIGNED', 'SYNTHETIC'],
  DSGNTonl: ['DESIGNED', 'TONAL'],
  DSGNVocl: ['DESIGNED', 'VOCAL'],
  DSGNWhsh: ['DESIGNED', 'WHOOSH'],
  ELECArc: ['ELECTRICITY', 'ARC'],
  ELECBuzz: ['ELECTRICITY', 'BUZZ & HUM'],
  ELECEmf: ['ELECTRICITY', 'ELECTROMAGNETIC'],
  ELECMisc: ['ELECTRICITY', 'MISC'],
  ELECSprk: ['ELECTRICITY', 'SPARKS'],
  ELECZap: ['ELECTRICITY', 'ZAP'],
  EQUIPBridle: ['EQUIPMENT', 'BRIDLE & TACK'],
  EQUIPMisc: ['EQUIPMENT', 'MISC'],
  EQUIPRec: ['EQUIPMENT', 'RECREATIONAL'],
  EQUIPSprt: ['EQUIPMENT', 'SPORT'],
  EQUIPTact: ['EQUIPMENT', 'TACTICAL'],
  EQUIPTech: ['EQUIPMENT', 'HITECH'],
  EXPLDsgn: ['EXPLOSIONS', 'DESIGNED'],
  EXPLMisc: ['EXPLOSIONS', 'MISC'],
  EXPLReal: ['EXPLOSIONS', 'REAL'],
  FARTDsgn: ['FARTS', 'DESIGNED'],
  FARTMisc: ['FARTS', 'MISC'],
  FARTReal: ['FARTS', 'REAL'],
  FEETAnml: ['FOOTSTEPS', 'ANIMAL'],
  FEETCrea: ['FOOTSTEPS', 'CREATURE'],
  FEETHmn: ['FOOTSTEPS', 'HUMAN'],
  FEETHors: ['FOOTSTEPS', 'HORSE'],
  FEETMisc: ['FOOTSTEPS', 'MISC'],
  FGHTBf: ['FIGHT', 'BODYFALL'],
  FGHTClth: ['FIGHT', 'CLOTH'],
  FGHTGrab: ['FIGHT', 'GRAB'],
  FGHTImpt: ['FIGHT', 'IMPACT'],
  FGHTMisc: ['FIGHT', 'MISC'],
  FIREBrst: ['FIRE', 'BURST'],
  FIREBurn: ['FIRE', 'BURNING'],
  FIRECrkl: ['FIRE', 'CRACKLE'],
  FIREGas: ['FIRE', 'GAS'],
  FIREIgn: ['FIRE', 'IGNITE'],
  FIREMisc: ['FIRE', 'MISC'],
  FIRESizz: ['FIRE', 'SIZZLE'],
  FIRETrch: ['FIRE', 'TORCH'],
  FIRETurb: ['FIRE', 'TURBULENT'],
  FIREWhsh: ['FIRE', 'WHOOSH'],
  FOLYClth: ['FOLEY', 'CLOTH'],
  FOLYFeet: ['FOLEY', 'FEET'],
  FOLYHand: ['FOLEY', 'HANDS'],
  FOLYMisc: ['FOLEY', 'MISC'],
  FOLYProp: ['FOLEY', 'PROP'],
  FOODCook: ['FOOD & DRINK', 'COOKING'],
  FOODDrnk: ['FOOD & DRINK', 'DRINKING'],
  FOODEat: ['FOOD & DRINK', 'EATING'],
  FOODGware: ['FOOD & DRINK', 'GLASSWARE'],
  FOODIngr: ['FOOD & DRINK', 'INGREDIENTS'],
  FOODKware: ['FOOD & DRINK', 'KITCHENWARE'],
  FOODMisc: ['FOOD & DRINK', 'MISC'],
  FOODPour: ['FOOD & DRINK', 'POUR'],
  FOODTware: ['FOOD & DRINK', 'TABLEWARE'],
  FRWKComr: ['FIREWORKS', 'COMMERCIAL'],
  FRWKMisc: ['FIREWORKS', 'MISC'],
  FRWKRec: ['FIREWORKS', 'RECREATIONAL'],
  GAMEArcd: ['GAMES', 'ARCADE'],
  GAMEBoard: ['GAMES', 'BOARD'],
  GAMECas: ['GAMES', 'CASINO'],
  GAMEMisc: ['GAMES', 'MISC'],
  GAMEVideo: ['GAMES', 'VIDEO'],
  GEOFuma: ['GEOTHERMAL', 'FUMAROLE'],
  GEOGeyser: ['GEOTHERMAL', 'GEYSER'],
  GEOLava: ['GEOTHERMAL', 'LAVA'],
  GEOMisc: ['GEOTHERMAL', 'MISC'],
  GEOMudpot: ['GEOTHERMAL', 'MUD POTS'],
  GLASBrk: ['GLASS', 'BREAK'],
  GLASCrsh: ['GLASS', 'CRASH & DEBRIS'],
  GLASFric: ['GLASS', 'FRICTION'],
  GLASHndl: ['GLASS', 'HANDLE'],
  GLASImpt: ['GLASS', 'IMPACT'],
  GLASMisc: ['GLASS', 'MISC'],
  GLASMvmt: ['GLASS', 'MOVEMENT'],
  GLASTonl: ['GLASS', 'TONAL'],
  GOREBlood: ['GORE', 'BLOOD'],
  GOREBone: ['GORE', 'BONE'],
  GOREBurn: ['GORE', 'BURN'],
  GOREFlsh: ['GORE', 'FLESH'],
  GOREMisc: ['GORE', 'MISC'],
  GOREOoze: ['GORE', 'OOZE'],
  GORESplt: ['GORE', 'SPLAT'],
  GORESqsh: ['GORE', 'SQUISH'],
  GORESrce: ['GORE', 'SOURCE'],
  GOREStab: ['GORE', 'STAB'],
  GUNAntq: ['GUNS', 'ANTIQUE'],
  GUNArtl: ['GUNS', 'ARTILLERY'],
  GUNAuto: ['GUNS', 'AUTOMATIC'],
  GUNCano: ['GUNS', 'CANNON'],
  GUNHndl: ['GUNS', 'HANDLE'],
  GUNMech: ['GUNS', 'MECHANISM'],
  GUNMisc: ['GUNS', 'MISC'],
  GUNPis: ['GUNS', 'PISTOL'],
  GUNRif: ['GUNS', 'RIFLE'],
  GUNShotg: ['GUNS', 'SHOTGUN'],
  GUNSupr: ['GUNS', 'SUPPRESSED'],
  GUNTech: ['GUNS', 'HITECH'],
  HAIL: ['WEATHER', 'HAIL'],
  HMNBlow: ['HUMAN', 'BLOW'],
  HMNBrth: ['HUMAN', 'BREATH'],
  HMNBurp: ['HUMAN', 'BURP'],
  HMNCough: ['HUMAN', 'COUGH'],
  HMNHart: ['HUMAN', 'HEARTBEAT'],
  HMNKiss: ['HUMAN', 'KISS'],
  HMNMisc: ['HUMAN', 'MISC'],
  HMNPee: ['HUMAN', 'PEE'],
  HMNSkin: ['HUMAN', 'SKIN'],
  HMNSneez: ['HUMAN', 'SNEEZE'],
  HMNSniff: ['HUMAN', 'SNIFF'],
  HMNSnor: ['HUMAN', 'SNORE'],
  HMNSpit: ['HUMAN', 'SPIT'],
  HMNVomit: ['HUMAN', 'VOMIT'],
  HORNAir: ['HORNS', 'AIR POWERED'],
  HORNCele: ['HORNS', 'CELEBRATION'],
  HORNMisc: ['HORNS', 'MISC'],
  HORNTrad: ['HORNS', 'TRADITIONAL'],
  ICEBrk: ['ICE', 'BREAK'],
  ICECrsh: ['ICE', 'CRASH & DEBRIS'],
  ICEFric: ['ICE', 'FRICTION'],
  ICEHndl: ['ICE', 'HANDLE'],
  ICEImpt: ['ICE', 'IMPACT'],
  ICEMisc: ['ICE', 'MISC'],
  ICEMvmt: ['ICE', 'MOVEMENT'],
  ICETonl: ['ICE', 'TONAL'],
  IR: ['ARCHIVED', 'IMPULSE RESPONSE'],
  LASRBeam: ['LASERS', 'BEAM'],
  LASRGun: ['LASERS', 'GUN'],
  LASRImpt: ['LASERS', 'IMPACT'],
  LASRMisc: ['LASERS', 'MISC'],
  LETHRCreak: ['LEATHER', 'CREAK'],
  LETHRHndl: ['LEATHER', 'HANDLE'],
  LETHRImpt: ['LEATHER', 'IMPACT'],
  LETHRMisc: ['LEATHER', 'MISC'],
  LETHRMvmt: ['LEATHER', 'MOVEMENT'],
  LIQBubl: ['LIQUID & MUD', 'BUBBLES'],
  LIQImpt: ['LIQUID & MUD', 'IMPACT'],
  LIQMisc: ['LIQUID & MUD', 'MISC'],
  LIQMvmt: ['LIQUID & MUD', 'MOVEMENT'],
  LIQSuct: ['LIQUID & MUD', 'SUCTION'],
  LPGRP: ['ARCHIVED', 'LOOP GROUP'],
  MACHAmus: ['MACHINES', 'AMUSEMENT'],
  MACHAntq: ['MACHINES', 'ANTIQUE'],
  MACHAppl: ['MACHINES', 'APPLIANCE'],
  MACHCnst: ['MACHINES', 'CONSTRUCTION'],
  MACHElev: ['MACHINES', 'ELEVATOR'],
  MACHEscl: ['MACHINES', 'ESCALATOR'],
  MACHFan: ['MACHINES', 'FAN'],
  MACHGrdn: ['MACHINES', 'GARDEN'],
  MACHGym: ['MACHINES', 'GYM'],
  MACHHvac: ['MACHINES', 'HVAC'],
  MACHInd: ['MACHINES', 'INDUSTRIAL'],
  MACHMech: ['MACHINES', 'MECHANISM'],
  MACHMed: ['MACHINES', 'MEDICAL'],
  MACHMisc: ['MACHINES', 'MISC'],
  MACHOffc: ['MACHINES', 'OFFICE'],
  MACHPump: ['MACHINES', 'PUMP'],
  MACHTech: ['MACHINES', 'HITECH'],
  MAGAngl: ['MAGIC', 'ANGELIC'],
  MAGElem: ['MAGIC', 'ELEMENTAL'],
  MAGEvil: ['MAGIC', 'EVIL'],
  MAGMisc: ['MAGIC', 'MISC'],
  MAGPoof: ['MAGIC', 'POOF'],
  MAGShim: ['MAGIC', 'SHIMMER'],
  MAGSpel: ['MAGIC', 'SPELL'],
  MECHClik: ['MECHANICAL', 'CLICK'],
  MECHGear: ['MECHANICAL', 'GEARS'],
  MECHHydr: ['MECHANICAL', 'HYDRAULIC & PNEUMATIC'],
  MECHLock: ['MECHANICAL', 'LOCK'],
  MECHLtch: ['MECHANICAL', 'LATCH'],
  MECHLvr: ['MECHANICAL', 'LEVER'],
  MECHMisc: ['MECHANICAL', 'MISC'],
  MECHPuly: ['MECHANICAL', 'PULLEY'],
  MECHRelay: ['MECHANICAL', 'RELAY'],
  MECHRolr: ['MECHANICAL', 'ROLLER'],
  MECHRtch: ['MECHANICAL', 'RATCHET'],
  MECHSwtch: ['MECHANICAL', 'SWITCH'],
  METLBrk: ['METAL', 'BREAK'],
  METLCrsh: ['METAL', 'CRASH & DEBRIS'],
  METLFric: ['METAL', 'FRICTION'],
  METLHndl: ['METAL', 'HANDLE'],
  METLImpt: ['METAL', 'IMPACT'],
  METLMisc: ['METAL', 'MISC'],
  METLMvmt: ['METAL', 'MOVEMENT'],
  METLTonl: ['METAL', 'TONAL'],
  MIX: ['ARCHIVED', 'MIX'],
  MOTRAntq: ['MOTORS', 'ANTIQUE'],
  MOTRComb: ['MOTORS', 'COMBUSTION'],
  MOTRElec: ['MOTORS', 'ELECTRIC'],
  MOTRMisc: ['MOTORS', 'MISC'],
  MOTRSrvo: ['MOTORS', 'SERVO'],
  MOTRTurb: ['MOTORS', 'TURBINE'],
  MOVEActv: ['MOVEMENT', 'ACTIVITY'],
  MOVEAnml: ['MOVEMENT', 'ANIMAL'],
  MOVECrea: ['MOVEMENT', 'CREATURE'],
  MOVECrwd: ['MOVEMENT', 'CROWD'],
  MOVEHmn: ['MOVEMENT', 'HUMAN'],
  MOVEInsc: ['MOVEMENT', 'INSECT'],
  MOVEMisc: ['MOVEMENT', 'MISC'],
  MOVEPres: ['MOVEMENT', 'PRESENCE'],
  MUSCBell: ['MUSICAL', 'BELLS'],
  MUSCBrass: ['MUSICAL', 'BRASS'],
  MUSCChim: ['MUSICAL', 'CHIME'],
  MUSCChor: ['MUSICAL', 'CHORAL'],
  MUSCExpr: ['MUSICAL', 'EXPERIMENTAL'],
  MUSCInst: ['MUSICAL', 'INSTRUMENT'],
  MUSCKeyd: ['MUSICAL', 'KEYED'],
  MUSCLoop: ['MUSICAL', 'LOOP'],
  MUSCMisc: ['MUSICAL', 'MISC'],
  MUSCPerc: ['MUSICAL', 'PERCUSSION'],
  MUSCPluck: ['MUSICAL', 'PLUCKED'],
  MUSCPrfm: ['MUSICAL', 'PERFORMANCE'],
  MUSCShake: ['MUSICAL', 'SHAKEN'],
  MUSCSmpl: ['MUSICAL', 'SAMPLE'],
  MUSCSong: ['MUSICAL', 'SONG & PHRASE'],
  MUSCStngr: ['MUSICAL', 'STINGER'],
  MUSCStr: ['MUSICAL', 'STRINGED'],
  MUSCSynth: ['MUSICAL', 'SYNTHESIZED'],
  MUSCTnprc: ['MUSICAL', 'PERCUSSION TUNED'],
  MUSCToy: ['MUSICAL', 'TOY'],
  MUSCWind: ['MUSICAL', 'WOODWIND'],
  MUSPBell: ['MUSICPROD', 'BELLS'],
  MUSPBrass: ['MUSICPROD', 'BRASS'],
  MUSPChim: ['MUSICPROD', 'CHIME'],
  MUSPChor: ['MUSICPROD', 'CHORAL'],
  MUSPExpr: ['MUSICPROD', 'EXPERIMENTAL'],
  MUSPImpr: ['MUSICPROD', 'IMPULSE RESPONSE'],
  MUSPInst: ['MUSICPROD', 'INSTRUMENT'],
  MUSPKeyd: ['MUSICPROD', 'KEYED'],
  MUSPLoop: ['MUSICPROD', 'LOOP'],
  MUSPMisc: ['MUSICPROD', 'MISC'],
  MUSPPerc: ['MUSICPROD', 'PERCUSSION'],
  MUSPPluck: ['MUSICPROD', 'PLUCKED'],
  MUSPPrfm: ['MUSICPROD', 'PERFORMANCE'],
  MUSPShake: ['MUSICPROD', 'SHAKEN'],
  MUSPSmpl: ['MUSICPROD', 'SAMPLE'],
  MUSPSong: ['MUSICPROD', 'SONG & PHRASE'],
  MUSPStngr: ['MUSICPROD', 'STINGER'],
  MUSPStr: ['MUSICPROD', 'STRINGED'],
  MUSPSynth: ['MUSICPROD', 'SYNTHESIZED'],
  MUSPTnprc: ['MUSICPROD', 'PERCUSSION TUNED'],
  MUSPToy: ['MUSICPROD', 'TOY'],
  MUSPWind: ['MUSICPROD', 'WOODWIND'],
  NATDAval: ['NATURAL DISASTER', 'AVALANCHE'],
  NATDMisc: ['NATURAL DISASTER', 'MISC'],
  NATDQuak: ['NATURAL DISASTER', 'EARTHQUAKE'],
  NATDThyp: ['NATURAL DISASTER', 'TYPHOON'],
  NATDTorn: ['NATURAL DISASTER', 'TORNADO'],
  NATDTsun: ['NATURAL DISASTER', 'TSUNAMI'],
  NATDVolc: ['NATURAL DISASTER', 'VOLCANO'],
  OBJBag: ['OBJECTS', 'BAG'],
  OBJBook: ['OBJECTS', 'BOOK'],
  OBJCoin: ['OBJECTS', 'COIN'],
  OBJCont: ['OBJECTS', 'CONTAINER'],
  OBJFash: ['OBJECTS', 'FASHION'],
  OBJFurn: ['OBJECTS', 'FURNITURE'],
  OBJGrdn: ['OBJECTS', 'GARDEN'],
  OBJGym: ['OBJECTS', 'GYM'],
  OBJHsehld: ['OBJECTS', 'HOUSEHOLD'],
  OBJJewl: ['OBJECTS', 'JEWELRY'],
  OBJKey: ['OBJECTS', 'KEYS'],
  OBJLug: ['OBJECTS', 'LUGGAGE'],
  OBJMed: ['OBJECTS', 'MEDICAL'],
  OBJMisc: ['OBJECTS', 'MISC'],
  OBJOffc: ['OBJECTS', 'OFFICE'],
  OBJPack: ['OBJECTS', 'PACKAGING'],
  OBJTape: ['OBJECTS', 'TAPE'],
  OBJUmbr: ['OBJECTS', 'UMBRELLA'],
  OBJWhled: ['OBJECTS', 'WHEELED'],
  OBJWrite: ['OBJECTS', 'WRITING'],
  OBJZipr: ['OBJECTS', 'ZIPPER'],
  PAPRFltr: ['PAPER', 'FLUTTER'],
  PAPRFric: ['PAPER', 'FRICTION'],
  PAPRHndl: ['PAPER', 'HANDLE'],
  PAPRImpt: ['PAPER', 'IMPACT'],
  PAPRMisc: ['PAPER', 'MISC'],
  PAPRRip: ['PAPER', 'RIP'],
  PAPRTonl: ['PAPER', 'TONAL'],
  PFX: ['ARCHIVED', 'PFX'],
  PLASBrk: ['PLASTIC', 'BREAK'],
  PLASCrsh: ['PLASTIC', 'CRASH & DEBRIS'],
  PLASFric: ['PLASTIC', 'FRICTION'],
  PLASHndl: ['PLASTIC', 'HANDLE'],
  PLASImpt: ['PLASTIC', 'IMPACT'],
  PLASMisc: ['PLASTIC', 'MISC'],
  PLASMvmt: ['PLASTIC', 'MOVEMENT'],
  PLASTonl: ['PLASTIC', 'TONAL'],
  PROD: ['ARCHIVED', 'PRODUCTION'],
  RAIN: ['RAIN', 'GENERAL'],
  RAINClth: ['RAIN', 'CLOTH'],
  RAINConc: ['RAIN', 'CONCRETE'],
  RAINGlas: ['RAIN', 'GLASS'],
  RAINInt: ['RAIN', 'INTERIOR'],
  RAINMetl: ['RAIN', 'METAL'],
  RAINPlas: ['RAIN', 'PLASTIC'],
  RAINVege: ['RAIN', 'VEGETATION'],
  RAINWatr: ['RAIN', 'WATER'],
  RAINWood: ['RAIN', 'WOOD'],
  RAW: ['ARCHIVED', 'RAW'],
  REF: ['ARCHIVED', 'REFERENCE'],
  ROBTMisc: ['ROBOTS', 'MISC'],
  ROBTMvmt: ['ROBOTS', 'MOVEMENT'],
  ROBTVox: ['ROBOTS', 'VOCAL'],
  ROCKBrk: ['ROCKS', 'BREAK'],
  ROCKCrsh: ['ROCKS', 'CRASH & DEBRIS'],
  ROCKFric: ['ROCKS', 'FRICTION'],
  ROCKHndl: ['ROCKS', 'HANDLE'],
  ROCKImpt: ['ROCKS', 'IMPACT'],
  ROCKMisc: ['ROCKS', 'MISC'],
  ROCKMvmt: ['ROCKS', 'MOVEMENT'],
  ROCKTonl: ['ROCKS', 'TONAL'],
  ROPECreak: ['ROPE', 'CREAK'],
  ROPEHndl: ['ROPE', 'HANDLE'],
  ROPEImpt: ['ROPE', 'IMPACT'],
  ROPEMisc: ['ROPE', 'MISC'],
  ROPEMvmt: ['ROPE', 'MOVEMENT'],
  RUBRCrsh: ['RUBBER', 'CRASH & DEBRIS'],
  RUBRFric: ['RUBBER', 'FRICTION'],
  RUBRHndl: ['RUBBER', 'HANDLE'],
  RUBRImpt: ['RUBBER', 'IMPACT'],
  RUBRMisc: ['RUBBER', 'MISC'],
  RUBRMvmt: ['RUBBER', 'MOVEMENT'],
  RUBRTonl: ['RUBBER', 'TONAL'],
  SCIAlrm: ['SCIFI', 'ALARM'],
  SCICmpt: ['SCIFI', 'COMPUTER'],
  SCIDoor: ['SCIFI', 'DOOR'],
  SCIEnrg: ['SCIFI', 'ENERGY'],
  SCIImpt: ['SCIFI', 'IMPACT'],
  SCIMach: ['SCIFI', 'MACHINE'],
  SCIMech: ['SCIFI', 'MECHANISM'],
  SCIMisc: ['SCIFI', 'MISC'],
  SCIRetro: ['SCIFI', 'RETRO'],
  SCIShip: ['SCIFI', 'SPACESHIP'],
  SCIVeh: ['SCIFI', 'VEHICLE'],
  SCIWeap: ['SCIFI', 'WEAPON'],
  SCNE: ['ARCHIVED', 'SCENE'],
  SNOWCrsh: ['SNOW', 'CRASH & DEBRIS'],
  SNOWFric: ['SNOW', 'FRICTION'],
  SNOWHndl: ['SNOW', 'HANDLE'],
  SNOWImpt: ['SNOW', 'IMPACT'],
  SNOWMisc: ['SNOW', 'MISC'],
  SNOWMvmt: ['SNOW', 'MOVEMENT'],
  SPRTClimb: ['SPORTS', 'CLIMBING'],
  SPRTCourt: ['SPORTS', 'COURT'],
  SPRTEqus: ['SPORTS', 'EQUESTRIAN'],
  SPRTField: ['SPORTS', 'FIELD'],
  SPRTGym: ['SPORTS', 'GYM'],
  SPRTIndor: ['SPORTS', 'INDOOR'],
  SPRTMisc: ['SPORTS', 'MISC'],
  SPRTSkate: ['SPORTS', 'SKATE'],
  SPRTTrck: ['SPORTS', 'TRACK & FIELD'],
  SPRTWatr: ['SPORTS', 'WATER'],
  SPRTWntr: ['SPORTS', 'WINTER'],
  STORM: ['WEATHER', 'STORM'],
  SWSH: ['SWOOSHES', 'SWISH'],
  TEST: ['ARCHIVED', 'TEST TONE'],
  THUN: ['WEATHER', 'THUNDER'],
  TMARK: ['ARCHIVED', 'TRADEMARKED'],
  TOOLGrdn: ['TOOLS', 'GARDEN'],
  TOOLHand: ['TOOLS', 'HAND'],
  TOOLMisc: ['TOOLS', 'MISC'],
  TOOLPneu: ['TOOLS', 'PNEUMATIC'],
  TOOLPowr: ['TOOLS', 'POWER'],
  TOONAnml: ['CARTOON', 'ANIMAL'],
  TOONBoing: ['CARTOON', 'BOING'],
  TOONClang: ['CARTOON', 'CLANG'],
  TOONCreak: ['CARTOON', 'CREAK'],
  TOONHorn: ['CARTOON', 'HORN'],
  TOONImpt: ['CARTOON', 'IMPACT'],
  TOONMach: ['CARTOON', 'MACHINE'],
  TOONMisc: ['CARTOON', 'MISC'],
  TOONMx: ['CARTOON', 'MUSICAL'],
  TOONPluk: ['CARTOON', 'PLUCK'],
  TOONPop: ['CARTOON', 'POP'],
  TOONShake: ['CARTOON', 'SHAKE'],
  TOONSplt: ['CARTOON', 'SPLAT'],
  TOONSqk: ['CARTOON', 'SQUEAK'],
  TOONStrch: ['CARTOON', 'STRETCH'],
  TOONSwsh: ['CARTOON', 'SWISH'],
  TOONTwang: ['CARTOON', 'TWANG'],
  TOONVeh: ['CARTOON', 'VEHICLE'],
  TOONVox: ['CARTOON', 'VOCAL'],
  TOONWarb: ['CARTOON', 'WARBLE'],
  TOONWhis: ['CARTOON', 'WHISTLE'],
  TOONZip: ['CARTOON', 'ZIP'],
  TOYElec: ['TOYS', 'ELECTRONIC'],
  TOYMech: ['TOYS', 'MECHANICAL'],
  TOYMisc: ['TOYS', 'MISC'],
  TRNBrake: ['TRAINS', 'BRAKE'],
  TRNClak: ['TRAINS', 'CLACK'],
  TRNDiesl: ['TRAINS', 'DIESEL'],
  TRNDoor: ['TRAINS', 'DOOR'],
  TRNElec: ['TRAINS', 'ELECTRIC'],
  TRNHorn: ['TRAINS', 'HORN'],
  TRNHspd: ['TRAINS', 'HIGH SPEED'],
  TRNInt: ['TRAINS', 'INTERIOR'],
  TRNMech: ['TRAINS', 'MECHANISM'],
  TRNMisc: ['TRAINS', 'MISC'],
  TRNSbwy: ['TRAINS', 'SUBWAY'],
  TRNSteam: ['TRAINS', 'STEAM'],
  TRNTram: ['TRAINS', 'TRAM'],
  UIAlert: ['USER INTERFACE', 'ALERT'],
  UIBeep: ['USER INTERFACE', 'BEEP'],
  UIClick: ['USER INTERFACE', 'CLICK'],
  UIData: ['USER INTERFACE', 'DATA'],
  UIGlitch: ['USER INTERFACE', 'GLITCH'],
  UIMisc: ['USER INTERFACE', 'MISC'],
  UIMvmt: ['USER INTERFACE', 'MOTION'],
  VEGEGras: ['VEGETATION', 'GRASS'],
  VEGELeaf: ['VEGETATION', 'LEAVES'],
  VEGEMisc: ['VEGETATION', 'MISC'],
  VEGETree: ['VEGETATION', 'TREE'],
  VEHAlrm: ['VEHICLES', 'ALARM'],
  VEHAntq: ['VEHICLES', 'ANTIQUE'],
  VEHAtv: ['VEHICLES', 'ATV'],
  VEHBike: ['VEHICLES', 'BICYCLE'],
  VEHBrake: ['VEHICLES', 'BRAKE'],
  VEHBus: ['VEHICLES', 'BUS'],
  VEHBy: ['VEHICLES', 'GENERIC BY'],
  VEHCar: ['VEHICLES', 'CAR'],
  VEHCnst: ['VEHICLES', 'CONSTRUCTION'],
  VEHDoor: ['VEHICLES', 'DOOR'],
  VEHElec: ['VEHICLES', 'ELECTRIC'],
  VEHEmrg: ['VEHICLES', 'EMERGENCY'],
  VEHFarm: ['VEHICLES', 'FARM'],
  VEHFrght: ['VEHICLES', 'FREIGHT'],
  VEHHorn: ['VEHICLES', 'HORN'],
  VEHInt: ['VEHICLES', 'INTERIOR'],
  VEHJalop: ['VEHICLES', 'JALOPY'],
  VEHMech: ['VEHICLES', 'MECHANISM'],
  VEHMil: ['VEHICLES', 'MILITARY'],
  VEHMisc: ['VEHICLES', 'MISC'],
  VEHMoto: ['VEHICLES', 'MOTORCYCLE'],
  VEHRace: ['VEHICLES', 'RACING'],
  VEHSirn: ['VEHICLES', 'SIREN'],
  VEHSkid: ['VEHICLES', 'SKID'],
  VEHSusp: ['VEHICLES', 'SUSPENSION'],
  VEHTire: ['VEHICLES', 'TIRE'],
  VEHTruck: ['VEHICLES', 'TRUCK VAN & SUV'],
  VEHUtil: ['VEHICLES', 'UTILITY'],
  VEHWagn: ['VEHICLES', 'WAGON'],
  VEHWndw: ['VEHICLES', 'WINDOW'],
  VOXAlien: ['VOICES', 'ALIEN'],
  VOXBaby: ['VOICES', 'BABY'],
  VOXCheer: ['VOICES', 'CHEER'],
  VOXChld: ['VOICES', 'CHILD'],
  VOXCry: ['VOICES', 'CRYING'],
  VOXEfrt: ['VOICES', 'EFFORTS'],
  VOXFem: ['VOICES', 'FEMALE'],
  VOXFutz: ['VOICES', 'FUTZED'],
  VOXHist: ['VOICES', 'HISTORICAL'],
  VOXLaff: ['VOICES', 'LAUGH'],
  VOXMale: ['VOICES', 'MALE'],
  VOXMisc: ['VOICES', 'MISC'],
  VOXReac: ['VOICES', 'REACTION'],
  VOXScrm: ['VOICES', 'SCREAM'],
  VOXSing: ['VOICES', 'SINGING'],
  VOXWhsp: ['VOICES', 'WHISPER'],
  WATRBubl: ['WATER', 'BUBBLES'],
  WATRDran: ['WATER', 'DRAIN'],
  WATRDrip: ['WATER', 'DRIP'],
  WATRFall: ['WATER', 'WATERFALL'],
  WATRFizz: ['WATER', 'FIZZ'],
  WATRFlow: ['WATER', 'FLOW'],
  WATRFoun: ['WATER', 'FOUNTAIN'],
  WATRImpt: ['WATER', 'IMPACT'],
  WATRLap: ['WATER', 'LAP'],
  WATRMisc: ['WATER', 'MISC'],
  WATRMvmt: ['WATER', 'MOVEMENT'],
  WATRPlmb: ['WATER', 'PLUMBING'],
  WATRPour: ['WATER', 'POUR'],
  WATRSplsh: ['WATER', 'SPLASH'],
  WATRSpray: ['WATER', 'SPRAY'],
  WATRStm: ['WATER', 'STEAM'],
  WATRSurf: ['WATER', 'SURF'],
  WATRTurb: ['WATER', 'TURBULENT'],
  WATRUndwtr: ['WATER', 'UNDERWATER'],
  WATRWave: ['WATER', 'WAVE'],
  WEAPArmr: ['WEAPONS', 'ARMOR'],
  WEAPArro: ['WEAPONS', 'ARROW'],
  WEAPAxe: ['WEAPONS', 'AXE'],
  WEAPBlnt: ['WEAPONS', 'BLUNT'],
  WEAPBow: ['WEAPONS', 'BOW'],
  WEAPKnif: ['WEAPONS', 'KNIFE'],
  WEAPMisc: ['WEAPONS', 'MISC'],
  WEAPPole: ['WEAPONS', 'POLEARM'],
  WEAPSiege: ['WEAPONS', 'SIEGE'],
  WEAPSwrd: ['WEAPONS', 'SWORD'],
  WEAPWhip: ['WEAPONS', 'WHIP'],
  WHSH: ['SWOOSHES', 'WHOOSH'],
  WHSTHmn: ['WHISTLES', 'HUMAN'],
  WHSTMech: ['WHISTLES', 'MECHANICAL'],
  WHSTMisc: ['WHISTLES', 'MISC'],
  WIND: ['WIND', 'GENERAL'],
  WINDDsgn: ['WIND', 'DESIGNED'],
  WINDGust: ['WIND', 'GUST'],
  WINDInt: ['WIND', 'INTERIOR'],
  WINDTonl: ['WIND', 'TONAL'],
  WINDTurb: ['WIND', 'TURBULENT'],
  WINDVege: ['WIND', 'VEGETATION'],
  WINGBird: ['WINGS', 'BIRD'],
  WINGCrea: ['WINGS', 'CREATURE'],
  WINGInsc: ['WINGS', 'INSECT'],
  WINGMisc: ['WINGS', 'MISC'],
  WIP: ['ARCHIVED', 'WORK IN PROGRESS'],
  WNDWCover: ['WINDOWS', 'COVERING'],
  WNDWHdwr: ['WINDOWS', 'HARDWARE'],
  WNDWKnck: ['WINDOWS', 'KNOCK'],
  WNDWMetl: ['WINDOWS', 'METAL'],
  WNDWMisc: ['WINDOWS', 'MISC'],
  WNDWPlas: ['WINDOWS', 'PLASTIC'],
  WNDWWood: ['WINDOWS', 'WOOD'],
  WOODBrk: ['WOOD', 'BREAK'],
  WOODCrsh: ['WOOD', 'CRASH & DEBRIS'],
  WOODFric: ['WOOD', 'FRICTION'],
  WOODHndl: ['WOOD', 'HANDLE'],
  WOODImpt: ['WOOD', 'IMPACT'],
  WOODMisc: ['WOOD', 'MISC'],
  WOODMvmt: ['WOOD', 'MOVEMENT'],
  WOODTonl: ['WOOD', 'TONAL'],
  WTF: ['ARCHIVED', 'WTF'],
  WTHR: ['WEATHER', 'MISC'],
};

/** One `ucs.alternatives` entry: an object from the current engine, or a packed
 *  string ("DOORKnck 0.31") from an older one. */
export type Alt = { category?: string; subcategory?: string; id?: string; probability?: number } | string | null | undefined;

/** The leading token of a legacy alternatives string ("DOORKnck 0.31" -> "DOORKnck"). */
export function altId(alt: Alt): string {
  if (alt && typeof alt === 'object') return alt.id || '';
  return String(alt || '').trim().split(/\s+/)[0] || '';
}

/** The UCS CATEGORY an alternatives entry belongs to, or '' if it cannot be resolved. */
export function altCategory(alt: Alt): string {
  if (alt && typeof alt === 'object') return alt.category || '';
  return UCS_BY_ID[altId(alt)]?.[0] || '';
}

/** The UCS SUBCATEGORY an alternatives entry belongs to, or '' if it cannot be resolved. */
export function altSubcategory(alt: Alt): string {
  if (alt && typeof alt === 'object') return alt.subcategory || '';
  return UCS_BY_ID[altId(alt)]?.[1] || '';
}

/** The posterior the matcher gave this runner-up, or NaN when it is not known. */
export function altProbability(alt: Alt): number {
  if (alt && typeof alt === 'object') {
    return typeof alt.probability === 'number' ? alt.probability : NaN;
  }
  const n = Number(String(alt || '').trim().split(/\s+/)[1]);
  return Number.isFinite(n) ? n : NaN;
}

/** Is there anything to show for this entry at all? */
export function hasAlt(alt: Alt): boolean {
  return !!altCategory(alt);
}
