

interface RenameTabProps {
  analysisResult: any[];
}

export default function RenameTab({ analysisResult }: RenameTabProps) {
  const handleGenerateScript = (type: 'ps1' | 'sh') => {
    if (analysisResult.length === 0) return;
    
    let scriptContent = '';
    
    if (type === 'ps1') {
      scriptContent += '# PowerShell Rename Script generated by Scanalyzer\n';
      analysisResult.forEach(item => {
        const safeGroup = (item.group || 'Other').replace(/[^a-zA-Z0-9]/g, '_');
        const pitch = Math.round(item.pitch_hz || 0);
        const newName = `${safeGroup}_${pitch}Hz_${item.name}`;
        scriptContent += `Rename-Item -Path "${item.path}" -NewName "${newName}" -ErrorAction SilentlyContinue\n`;
      });
    } else {
      scriptContent += '#!/bin/bash\n';
      scriptContent += '# Bash Rename Script generated by Scanalyzer\n\n';
      analysisResult.forEach(item => {
        const safeGroup = (item.group || 'Other').replace(/[^a-zA-Z0-9]/g, '_');
        const pitch = Math.round(item.pitch_hz || 0);
        const newName = `${safeGroup}_${pitch}Hz_${item.name}`;
        scriptContent += `mv "${item.path}" "\$(dirname "${item.path}")/${newName}" 2>/dev/null || true\n`;
      });
    }

    const blob = new Blob([scriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `rename_samples.${type}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ marginTop: '1rem', background: 'rgba(0,0,0,0.2)', borderRadius: '12px', padding: '2rem', border: '1px solid var(--border-color)', textAlign: 'center' }}>
      <h3 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>Batch Rename Scripts</h3>
      <p className="text-secondary" style={{ marginBottom: '2rem' }}>
          Instead of modifying your files directly, we can generate a script you can run offline. 
          This script will rename all analyzed files in their folders to a standard format: <code>Group_Pitch_OriginalName.wav</code>
      </p>
      
      <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }}>
          <button 
              className="btn primary" 
              onClick={() => handleGenerateScript('ps1')}
              disabled={analysisResult.length === 0}
          >
              Generate PowerShell (.ps1)
          </button>
          <button 
              className="btn primary" 
              onClick={() => handleGenerateScript('sh')}
              disabled={analysisResult.length === 0}
          >
              Generate Bash (.sh)
          </button>
      </div>
      
      {analysisResult.length === 0 && (
          <p style={{ marginTop: '1.5rem', color: 'var(--accent-secondary)' }}>
              Please scan a folder or load a .PEAK file first.
          </p>
      )}
    </div>
  );
}
